
name: Backup Game Saves
on: 
  push:
    paths:
      - 'game-saves/**' # Adjust the path accordingly

jobs:
  backup:
    name: Backup Game Saves
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit Changes for Game Saves Backup
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated game saves backup"
          git push
