name: Deploy Docker Container

on: workflow_dispatch # or push, pull_request, schedule, repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Docker and Docker-Compose
      run: |

        # Install Docker and Docker-Compose on Ubuntu 20.04 with best practices
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker $USER
        sudo systemctl enable docker
        
        # Complete configuration Ubuntu: Startship, Nerd-Fonts, LSD, ZSH, Oh-My-Zsh
        # Update your software repositories.
        sudo apt-get update
        sudo apt-get upgrade

        # Install Git.
        sudo apt-get install -y git
        git clone https://github.com/pobruno/monga-server-handle

        # Install Powerline
        #cd monga-server-handle/.config/Server-Ubuntu
        #./install_powerline.sh



    - name: Verify Docker Installation
      run: |
        docker --version
        docker-compose --version
    - name: Run Portainer Docker Container
      run: |
        docker run -d -p 9090:9090 --name portainer-web-docker -v data:/data -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer --restart unless-stopped
    - name: Clone Git Repository
      run: |
        git clone https://github.com/pobruno/monga-server-handle
        cd monga-server-handle/.config/Server-Ubuntu
        ./install_powerline.sh
        ./install_terminal.sh
        ./install_profile.sh







      